builds:
- skip: true
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other work
      order: 999
milestones:
  - close: true