name: test

on:
  push:
    branches:
      - master
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: dotfiles
      - name: Setup structure
        run: |
          # we expect the file directory to be in $HOME
          mv dotfiles ~/.dotfiles
          # for pulling from  git with brew we need a dummy key in the agent
          ssh-keygen -b 4096 -t rsa -f ~/.ssh/dummy-key -q -N ""
          chmod 0600 ~/.ssh/dummy-key
          ssh-add ~/.ssh/dummy-key
          ssh-add -l
      - name: Installing brew
        run: |
          ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew --version
      - name: Install prerequisites
        run: |
          brew install git fish grc
          git config --global user.email "test@example.com"
      - name: Install dotfiles
        run: |
          cd ~/.dotfiles
          ./script/bootstrap.fish
      - name: Install recommended software
        run: |
          brew install git-delta fzf gh kubectx starship zoxide
      - name: Set macOS defaults
        run: |
          ~/.dotfiles/macos/set-defaults.sh
